.TH LINTHESIA "1" "January 2022" "linthesia" "User Commands"
.SH NAME
linthesia \- A game of playing music
.SH SYNOPSIS
.B linthesia
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.B linthesia
Linthesia is a game of playing music. Select a midi file...
.SH OPTIONS
.TP
\fB\-f\fR
load files
.TP
\fB\-w\fR
start in window mode
.TP
\fB\-W\fR
start in full screen mode
.TP
\fB\--min-key\fR
define min key
.TP
\fB\--max-key\fR
define max key
.TP
\fB\-\-lib-path\fR
define directory for music library
.TP
\fB\-\-reset-lib-path\fR
reset directory for music library to default
.TP
\fB\-\-help\fR
Show help options
.TP
\fB\-\-version\fR
Show the applications version
.RE
.SH AUTHORS
.br
Alberto Fanjul  <albertofanjul@gmail.com>
